### ISSUE TITLE
Error in limitation description and duplicates in 'mandates'

### ISSUE THREAD

**Issue by krkurz** [StatePol/Database#4]
Thanks a lot for the database! That's really a great addition.

I've found two issues:

- In your description of the limitations you write that there are 0 politicians without an URL, I think that's a typo (https://statepol.github.io/Database/limitations.html).
- There are some duplicates in the 'mandates' list, e.g. /wiki/Felix _Hodapp-bw-10

All the best,
Kira

**Comment by elias-koch** [comment]
Dear @krkurz, 
we only just saw your comment – thank you so much for pointing this out! Both errors are easily fixed and we will upload an updated version of the database in the coming days without the duplicates. We'll get back to you as soon as it's published!
Best regards to Freiburg!
Elias

**Comment by danielkuhlen** [comment]
The updated version (1.0.4) is now available, and both errors should be fixed. Thank you again for pointing this out!
